language: node_js

node_js:
  - "8"

env:
  - SET=android SYS=browserstack
  - SET=chrome SYS=browserstack
  - SET=edge SYS=browserstack
  - SET=firefox SYS=browserstack
  - SET=internet-explorer SYS=browserstack
  - SET=ios SYS=browserstack
  - SET=opera SYS=browserstack
  - SET=safari SYS=browserstack
  - SET=windows-phone SYS=browserstack
  - SET=yandex SYS=browserstack

before_script:
  - ./node_modules/.bin/cbtr-browserstack-update

cache:
  directories:
    - "node_modules"

addons:
  hosts:
    - build.cross-browser-tests-runner.org
