language: node_js

node_js:
  - "8"

branches:
  only:
  - master

env:
# groups of 3 parallel
 - SET=android-browser SYS=browserstack
 - SET=android-browser SYS=crossbrowsertesting
 - SET=android-browser SYS=saucelabs
 - SET=chrome-osx-el-capitan SYS=browserstack
 - SET=chrome-osx-el-capitan SYS=crossbrowsertesting
 - SET=chrome-osx-el-capitan SYS=saucelabs
 - SET=chrome-osx-mavericks SYS=browserstack
 - SET=chrome-osx-mavericks SYS=crossbrowsertesting
 - SET=chrome-osx-mavericks SYS=saucelabs
 - SET=chrome-osx-yosemite SYS=browserstack
 - SET=chrome-osx-yosemite SYS=crossbrowsertesting
 - SET=chrome-osx-yosemite SYS=saucelabs
 - SET=chrome-win-10 SYS=browserstack
 - SET=chrome-win-10 SYS=crossbrowsertesting
 - SET=chrome-win-10 SYS=saucelabs
 - SET=chrome-win-7 SYS=browserstack
 - SET=chrome-win-7 SYS=saucelabs
 - SET=chrome-win-7-beta SYS=crossbrowsertesting
 - SET=chrome-win-8 SYS=browserstack
 - SET=chrome-win-8 SYS=saucelabs
 - SET=chrome-win-8-preview SYS=crossbrowsertesting
 - SET=chrome-win-8.1 SYS=browserstack
 - SET=chrome-win-8.1 SYS=crossbrowsertesting
 - SET=chrome-win-8.1 SYS=saucelabs
 - SET=edge SYS=browserstack
 - SET=edge SYS=crossbrowsertesting
 - SET=edge SYS=saucelabs
 - SET=firefox-osx-el-capitan SYS=browserstack
 - SET=firefox-osx-el-capitan SYS=crossbrowsertesting
 - SET=firefox-osx-el-capitan SYS=saucelabs
 - SET=firefox-osx-mavericks SYS=browserstack
 - SET=firefox-osx-mavericks SYS=crossbrowsertesting
 - SET=firefox-osx-mavericks SYS=saucelabs
 - SET=firefox-osx-sierra SYS=browserstack
 - SET=firefox-osx-sierra SYS=crossbrowsertesting
 - SET=firefox-osx-sierra SYS=saucelabs
 - SET=firefox-win-10 SYS=browserstack
 - SET=firefox-win-10 SYS=crossbrowsertesting
 - SET=firefox-win-10 SYS=saucelabs
 - SET=firefox-win-7 SYS=browserstack
 - SET=firefox-win-7 SYS=saucelabs
 - SET=firefox-win-7-beta SYS=crossbrowsertesting
 - SET=firefox-win-8 SYS=browserstack
 - SET=firefox-win-8 SYS=saucelabs
 - SET=firefox-win-8-preview SYS=crossbrowsertesting
 - SET=firefox-win-8.1 SYS=browserstack
 - SET=firefox-win-8.1 SYS=crossbrowsertesting
 - SET=firefox-win-8.1 SYS=saucelabs
 - SET=internet-explorer SYS=browserstack
 - SET=internet-explorer SYS=crossbrowsertesting
 - SET=internet-explorer SYS=saucelabs
 - SET=mobile-safari SYS=browserstack
 - SET=mobile-safari SYS=crossbrowsertesting
 - SET=mobile-safari-11.0 SYS=saucelabs
 - SET=safari SYS=browserstack
 - SET=safari SYS=crossbrowsertesting
 - SET=safari SYS=saucelabs
 - SET=chrome-osx-lion SYS=browserstack
 - SET=chrome-osx-lion SYS=crossbrowsertesting
 - SET=mobile-safari-10.0 SYS=saucelabs
 - SET=chrome-osx-mountain-lion SYS=browserstack
 - SET=chrome-osx-mountain-lion SYS=crossbrowsertesting
 - SET=mobile-safari-10.2 SYS=saucelabs
 - SET=chrome-osx-sierra SYS=browserstack
 - SET=chrome-osx-sierra SYS=saucelabs
 - SET=mobile-safari-10.3 SYS=saucelabs
 - SET=chrome-osx-high-sierra SYS=browserstack
 - SET=chrome-ubuntu-oneiric SYS=crossbrowsertesting
 - SET=chrome-linux SYS=saucelabs
 - SET=chrome-win-xp SYS=browserstack
 - SET=chrome-win-xp-sp2 SYS=crossbrowsertesting
 - SET=mobile-safari-8.1 SYS=saucelabs
 - SET=firefox-osx-high-sierra SYS=browserstack
 - SET=firefox-osx-high-sierra SYS=crossbrowsertesting
 - SET=mobile-safari-8.2 SYS=saucelabs
 - SET=firefox-osx-lion SYS=browserstack
 - SET=firefox-osx-lion SYS=crossbrowsertesting
 - SET=mobile-safari-8.3 SYS=saucelabs
 - SET=firefox-osx-mountain-lion SYS=browserstack
 - SET=firefox-osx-mountain-lion SYS=crossbrowsertesting
 - SET=mobile-safari-8.4 SYS=saucelabs
 - SET=firefox-osx-yosemite SYS=browserstack
 - SET=firefox-osx-yosemite SYS=saucelabs
 - SET=mobile-safari-9.0 SYS=saucelabs
 - SET=firefox-win-xp SYS=browserstack
 - SET=firefox-win-xp-sp2 SYS=crossbrowsertesting
 - SET=mobile-safari-9.1 SYS=saucelabs
 - SET=chrome-osx-snow-leopard SYS=browserstack
 - SET=firefox-ubuntu-oneiric SYS=crossbrowsertesting
 - SET=firefox-linux SYS=saucelabs
 - SET=opera-osx-el-capitan SYS=browserstack
 - SET=opera-osx-el-capitan SYS=crossbrowsertesting
 - SET=mobile-safari-9.2 SYS=saucelabs
 - SET=opera-osx-high-sierra SYS=browserstack
 - SET=opera-osx-high-sierra SYS=crossbrowsertesting
 - SET=mobile-safari-9.3 SYS=saucelabs
# groups of 2 parallel
 - SET=opera-osx-lion SYS=browserstack
 - SET=opera-osx-lion SYS=crossbrowsertesting
 - SET=opera-osx-mavericks SYS=browserstack
 - SET=opera-osx-mavericks SYS=crossbrowsertesting
 - SET=opera-osx-mountain-lion SYS=browserstack
 - SET=opera-osx-mountain-lion SYS=crossbrowsertesting
 - SET=opera-osx-sierra SYS=browserstack
 - SET=opera-osx-sierra SYS=crossbrowsertesting
 - SET=opera-win-10 SYS=browserstack
 - SET=opera-win-10 SYS=crossbrowsertesting
 - SET=opera-win-7 SYS=browserstack
 - SET=opera-win-7-beta SYS=crossbrowsertesting
 - SET=opera-win-8 SYS=browserstack
 - SET=opera-win-8-preview SYS=crossbrowsertesting
 - SET=opera-win-8.1 SYS=browserstack
 - SET=opera-win-8.1 SYS=crossbrowsertesting
 - SET=opera-win-xp SYS=browserstack
 - SET=opera-win-xp-sp2 SYS=crossbrowsertesting
 - SET=windows-phone SYS=browserstack
 - SET=windows-phone SYS=crossbrowsertesting
 - SET=firefox-osx-snow-leopard SYS=browserstack
 - SET=firefox-win-7-x64 SYS=crossbrowsertesting
 - SET=opera-osx-snow-leopard SYS=browserstack
 - SET=opera-win-7-x64 SYS=crossbrowsertesting
 - SET=opera-osx-yosemite SYS=browserstack
 - SET=opera-ubuntu-oneiric SYS=crossbrowsertesting
 - SET=yandex SYS=browserstack
 - SET=opera-win-vista-home SYS=crossbrowsertesting
# single ones
 - SET=chrome-win-7-x64 SYS=crossbrowsertesting
 - SET=chrome-win-vista-home SYS=crossbrowsertesting
 - SET=chrome-win-xp-sp3 SYS=crossbrowsertesting
 - SET=chrome-x64-osx-el-capitan SYS=crossbrowsertesting
 - SET=chrome-x64-osx-high-sierra SYS=crossbrowsertesting
 - SET=chrome-x64-osx-lion SYS=crossbrowsertesting
 - SET=chrome-x64-osx-mavericks SYS=crossbrowsertesting
 - SET=chrome-x64-osx-mountain-lion SYS=crossbrowsertesting
 - SET=chrome-x64-osx-sierra SYS=crossbrowsertesting
 - SET=chrome-x64-osx-yosemite SYS=crossbrowsertesting
 - SET=chrome-x64-ubuntu-trusty SYS=crossbrowsertesting
 - SET=chrome-x64-ubuntu-vivid SYS=crossbrowsertesting
 - SET=chrome-x64-win-10 SYS=crossbrowsertesting
 - SET=chrome-x64-win-7-x64 SYS=crossbrowsertesting
 - SET=chrome-x64-win-8-preview SYS=crossbrowsertesting
 - SET=chrome-x64-win-8.1 SYS=crossbrowsertesting
 - SET=chromium SYS=crossbrowsertesting
 - SET=dolphin-mobile SYS=crossbrowsertesting
 - SET=firefox-mobile SYS=crossbrowsertesting
 - SET=firefox-ubuntu-trusty SYS=crossbrowsertesting
 - SET=firefox-ubuntu-vivid SYS=crossbrowsertesting
 - SET=firefox-win-vista-home SYS=crossbrowsertesting
 - SET=firefox-win-xp-sp3 SYS=crossbrowsertesting
 - SET=firefox-x64-win-10 SYS=crossbrowsertesting
 - SET=firefox-x64-win-7-x64 SYS=crossbrowsertesting
 - SET=firefox-x64-win-8-preview SYS=crossbrowsertesting
 - SET=firefox-x64-win-8.1 SYS=crossbrowsertesting
 - SET=internet-explorer-x64 SYS=crossbrowsertesting
 - SET=maxthon-mobile SYS=crossbrowsertesting
 - SET=maxthon-mobile-hd SYS=crossbrowsertesting
 - SET=mozilla SYS=crossbrowsertesting
 - SET=netscape SYS=crossbrowsertesting
 - SET=opera-mini SYS=crossbrowsertesting
 - SET=opera-mini-for-ios SYS=crossbrowsertesting
 - SET=opera-mobile SYS=crossbrowsertesting
 - SET=opera-win-xp-sp3 SYS=crossbrowsertesting
 - SET=samsung-browser SYS=crossbrowsertesting
 - SET=sleipnir-mobile SYS=crossbrowsertesting
 - SET=uc-browser SYS=crossbrowsertesting
 - SET=aol-explorer SYS=crossbrowsertesting
 - SET=blackberry-browser SYS=crossbrowsertesting
 - SET=camino SYS=crossbrowsertesting
 - SET=chrome-for-ios SYS=crossbrowsertesting
 - SET=chrome-mobile SYS=crossbrowsertesting

cache:
  directories:
    - "node_modules"

addons:
  hosts:
    - build.cross-browser-tests-runner.org
