language: node_js

node_js:
  - "stable"

branches:
  only:
  - master

env:
  - BROWSER="android-browser" PLATFORM=saucelabs
  - BROWSER="chrome" PLATFORM=saucelabs
  - BROWSER="edge" PLATFORM=saucelabs
  - BROWSER="firefox" PLATFORM=saucelabs
  - BROWSER="internet-explorer" PLATFORM=saucelabs
  - BROWSER="mobile-safari" PLATFORM=saucelabs
  - BROWSER="safari" PLATFORM=saucelabs

cache:
  directories:
    - "node_modules"

addons:
  hosts:
    - build.cross-browser-tests-runner.org
